version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=prlab3
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:management
    container_name: my_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  ftp_server:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      FTP_USER_NAME: testuser
      FTP_USER_PASS: testpass
      FTP_USER_HOME: /home/testuser
    volumes:
      - ftp_data:/home/testuser
    networks:
      - app-network
  app:
    image: prlab3
    container_name: spring_app
    depends_on:
      - db
      - rabbitmq
      - ftp_server
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/prlab3
      SPRING_DATASOURCE_PASSWORD: ''
      SPRING_DATASOURCE_USERNAME: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MAILERSEND_API_KEY: 'PASTE THE TOKEN HERE'
      NODE_ID: 0
      NODE_PEERS: ''
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  db_data:
  ftp_data:

networks:
  app-network:
    driver: bridge