version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=prlab3
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  app1:
    image: prlab3
    container_name: spring_app_1
    depends_on:
      - db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/prlab3
      SPRING_DATASOURCE_PASSWORD: ''
      SPRING_DATASOURCE_USERNAME: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MAILERSEND_API_KEY: 'PASTE THE TOKEN HERE'
      NODE_ID: 1
      NODE_PEERS: '2,3'
    ports:
      - "8080:8080"
    networks:
      - app-network
  app2:
    image: prlab3
    container_name: spring_app_2
    depends_on:
      - db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/prlab3
      SPRING_DATASOURCE_PASSWORD: ''
      SPRING_DATASOURCE_USERNAME: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MAILERSEND_API_KEY: 'PASTE THE TOKEN HERE'
      NODE_ID: 2
      NODE_PEERS: '1,3'
    ports:
      - "8081:8080"
    networks:
      - app-network
  app3:
    image: prlab3
    container_name: spring_app_3
    depends_on:
      - db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/prlab3
      SPRING_DATASOURCE_PASSWORD: ''
      SPRING_DATASOURCE_USERNAME: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MAILERSEND_API_KEY: 'PASTE THE TOKEN HERE'
      NODE_ID: 3
      NODE_PEERS: '1,2'
    ports:
      - "8082:8080"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge