version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: lab3_intermediary_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  ftp_server:
    image: stilliard/pure-ftpd:hardened
    container_name: lab3_intermediary_ftp_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      FTP_USER_NAME: testuser
      FTP_USER_PASS: testpass
      FTP_USER_HOME: /home/testuser
    volumes:
      - ftp_data:/home/testuser
    networks:
      - app-network
  app:
    image: prlab3_intermediary_server
    container_name: lab3_intermediary_server
    depends_on:
      - rabbitmq
      - ftp_server
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  ftp_data:

networks:
  app-network:
    driver: bridge